name: CI Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: hicham


    env:
      IMAGE_NAME: ci-html-demo
      IMAGE_TAG: latest
      DOCKER_REGISTRY: moisawade

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin